### ISSUE TITLE
Try quticon visualization for Jenkins in a Praqma or customer setup

### ISSUE THREAD

**Issue by buep** [Praqma/quticon_visualization#13]
I'm planning to see if this implementation solves my original use-case described in https://github.com/Praqma/praqma-rnd/issues/11 and further if I can use it in a real environment at a customer.

The work will be time boxed and delivery will be inputs to the readme and possible new issues to extend or improve what is already implemented.

**Comment by Andrey9kin** [comment]
Super. Let me know if you need any help and please document issues you
encountered as GH issues

**Comment by buep** [comment]
@Andrey9kin - isn't this plugin almost the same? https://plugins.jenkins.io/statistics-gatherer

**Comment by Andrey9kin** [comment]
@buep let's start from that it is not invented here :))

I think it is a good finding and we should definitely look at it but a bit later. Since right now I'm trying to understand what exactly to collect, in what format and what ElasticSearch can do with data. 
When I have this understanding then we should revisit the plugin.

**Comment by buep** [comment]
This is done - can't get it to work. I'm missing tests, more docs and some compatibility list, since it seems to matter what environment I use.
Tests should also explain a working environment setup.

I filed issue #16 and will fix the docs etc. as part or follow up to that.
